# basic options

pages_list:  
  Home: '/'  
  About Us: '/aboutus.html'
  Class List: '/classlist.html'

title: Ann Arbor High School Pioneers
description: Class of 1963
logo: AAHS63
address1: 7220 Hashley Road
address2: Manchester, MI 48158

# Build settings

markdown: kramdown
theme: jekyll-theme-cayman
