# basic options

pages_list:  
  Home: '/'  
  About Us: '/aboutus.html'
  Class List: '/classlist.html'

title: Ann Arbor High School Pioneers
subtitle: Class of 1963

# Build settings

markdown: kramdown
theme: jekyll-theme-cayman
